version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm ci -f
            fi
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run test:ci
      - store_artifacts:
          path: coverage
      - run:
          name: install sonar scanner
          command: sudo npm install -g sonarqube-scanner@2.5.0
      - run:
          name: Run SonarScanner
          command: sonar-scanner